### ISSUE TITLE
Typo in manual overrides stops Fabio from updating routes

### ISSUE THREAD

**Issue by thepolina** [fabiolb/fabio#399] opened 2017-12-03 23:44 UTC
I noticed pretty weird issue:
If you add route to manual overrides with a typo, Fabio doesn't give you error message when you save it. 
This message is appearing in logs:
`2017/12/01 05:48:32 [WARN] line 26: syntax error: 'route add' invalid`

Also it seems that Fabio stops updating routes since it has a typo in manual overrides. When services go down and come back with a new IP address Fabio keeps pointing on the old one.

Any help with this issue would be appreciated.
Cheers

**Comment by magiconair** [comment] 2017-12-03 23:51
Unfortunately, this is a known issue and a duplicate of #282. Fabio should probably ignore the bad line and log the syntax error instead of blocking all updates. Neither approach is fully satisfactory but not updating the routing table at all because of a typo has the bigger impact. I'm going to close this as duplicate but please subscribe to #282 for updates.

Duplicate of #282

**Closed by magiconair** 2017-12-03 23:52 UTC
