### ISSUE TITLE
More than one fabio instance decreases system performance.

### ISSUE THREAD

**Issue by mokonn** [fabiolb/fabio#361] opened 2017-09-25 14:42 UTC
Adding second fabio to our infrastucture results decreasing performace.
Time to handle requests increase up to 20 seconds.

Fabio version 1.3.4

**Comment by magiconair** [comment] 2017-09-25 16:01
This sounds really weird. We - and all customers I know - are running multiple fabio instances with no noticeable problems. Are these the same types of machines? Same network? Same load? Congestion? Noisy neighbors?

**Comment by magiconair** [comment] 2017-10-01 04:05
I'm curious but also quite suspicious about this claim. There are some very large customers using fabio with significant throughput. This would have shown up sooner. If you have additional data to support that fabio is the root cause please provide them and I'll follow up. In the meantime I'll close this ticket.

**Closed by magiconair** 2017-10-01 04:05 UTC
