### ISSUE TITLE
Expose Fabio metrics via Prometheus

### ISSUE THREAD

**Issue by DavidJeche** [fabiolb/fabio#532] opened 2018-08-10 14:13 UTC
Fabio looks like a really impressive proxy for hashicorp related systems.

However I have seen that the metrics exposed by fabio do no include prometheus. The reason for this issue is to request whether anyone would like to work on adding Prometheus metrics to the program. 

We will need to perform some instrumentation. I am looking for someone with go expertise. Please let me know if anyone would like to work on this.

**Comment by leprechau** [comment] 2018-08-10 14:19
Closing this as a duplicate of #211 ... please feel free to  comment on that issue.

**Closed by leprechau** 2018-08-10 14:19 UTC
