### ISSUE TITLE
1.5.0 config compatibility problem 

### ISSUE THREAD

**Issue by pipozzz** [fabiolb/fabio#305] opened 2017-06-13 13:32 UTC
Hello,

I have a problem with fabio upgrade to the latest 1.5.0

this is my config:
```
proxy.cs = cs=consul-cs;type=consul;cert=http://localhost:8500/v1/kv/ssl?token=token
proxy.addr = :443;cs=consul-cs,:80,:2375;proto=tcp+sni
```

I see in output just this:
2017/06/13 13:27:03 [FATAL] 1.5.0. =

Where could be a problem?

Thank you.

**Comment by magiconair** [comment] 2017-06-13 14:49
I've refactored the code for parsing the `proxy.addr` values. Let me have a look.

**Comment by magiconair** [comment] 2017-06-13 15:14
The problem is the second `=` in the `proxy.cs` line. This is a bug in the parseKVSlice code. I'll fix it.

**Comment by magiconair** [comment] 2017-06-13 15:33
I've pushed a fix in the `issue-305` branch. Could you check whether this fixes the problem for you?

**Comment by pipozzz** [comment] 2017-06-13 18:22
Great, I checked that, everything works properly, thanks

**Comment by pipozzz** [comment] 2017-07-03 09:32
When do you plan to merge that fix to new release?
Thanks

**Comment by magiconair** [comment] 2017-07-03 10:39
Today or tomorrow. Is that soon enough?

**Comment by pipozzz** [comment] 2017-07-03 10:40
Great !!, I'm just asking

Thanks

**Comment by pipozzz** [comment] 2017-07-07 09:48
Did you forget on this issue in new release?
I would like to use latest version of fabio, if possible.

**Comment by magiconair** [comment] 2017-07-07 10:24
Damn. Yes. I'll push a 1.5.2 soon. Might be early next week though.

**Comment by pipozzz** [comment] 2017-07-07 10:25
Thanks, it would help me a lot 👍

**Closed** 2017-07-07 10:39 UTC
Labels: bug
