### ISSUE TITLE
Remove third-party cookie and script requirements from frontend

### ISSUE THREAD

**Issue by khimaros** [fabiolb/fabio#642] opened 2019-04-16 05:56 UTC
Attempt to use the Fabio frontend with uMatrix enabled.

Ideally, Javascript and cookies would only be required from first-party sources.

Instead we see:

```
cookie: cloudflare.com
script: cdnjs.cloudflare.com, code.jquery.com
```

**Comment by pschultz** [comment] 2019-04-16 07:35
Closing as duplicate of #502.

**Closed by pschultz** 2019-04-16 07:35 UTC
