### ISSUE TITLE
Websocket proxy timeouts

### ISSUE THREAD

**Issue by imcitius** [fabiolb/fabio#518] opened 2018-07-03 15:24 UTC
Hello!

I'm trying to load-balance websocket server using fabio, and get strange behavior.
Some times test websocket client on python (infinite loop, trying to connect to websocket, subscribe for events, and get few events) throws exception:
```
can't connect to websocket (Connection is already closed.)
```

In fabio's log I see this:
```
-- [ERROR] Error reading handshake for http://ws.app.com:80/ws/58a1dd37595c85.80547695: read tcp 10.0.0.1:33529->10.0.0.2:80: i/o timeout
-- invalid log msg: 2018/07/03 22:05:57 http: response.WriteHeader on hijacked connection
-- invalid log msg: 2018/07/03 22:05:57 http: response.Write on hijacked connection
```

But the very same setup with traefik instead fabio, works perfectly.

May I miss something?

Thanks.

**Comment by leprechau** [comment] 2018-07-03 15:34
What happens if you run the same test through fabio and direct to the backend at the same time?  Does the call through fabio fail and the call direct work or do they both fail at the same time?

**Comment by leprechau** [comment] 2018-07-03 15:35
The error you posted from the log looks like fabio (10.0.0.1) timed out during the tcp handshake while trying to establish a connection to the backend (10.0.0.2) on over port 80 tcp.

**Comment by leprechau** [comment] 2018-07-03 15:37
There could be many reasons including resource exhaustion.  Is the test client and/or the backend properly closing the socket?  Could you be running out of available outbound ports?  Is it an open file handle limit?

**Comment by imcitius** [comment] 2018-07-03 15:43
I will test direct test without lb, and update this thread.

fabio/traefik and ws server is on same lan in all cases, so I think any network related problems should hit traefik as well.

Concerning system resources - fabio has 100 000 descriptors available, and there is no production load on it now, so fabio's resources cannot exhaust.
Same with network, problems on the ws server side should hit traefik as well.

Also, I think good traefik's work cannot be just bad test or randomness, because traefik works for month, and problem with fabio arise immediately after we try to put it in the chain.

**Comment by leprechau** [comment] 2018-07-03 15:50
Wasn't trying to invalidate your results.  Just trying to think through the problem to identify the root cause.  The error above is generated from the underlying golang network library.  This could be because something isn't closing sockets.  When the test fails does it fail once or repeatedly?  Could you capture a `netstat -untap|grep fabio` output on the fabio host when the tests are failing?

**Comment by imcitius** [comment] 2018-07-03 16:08
No offence, please excuse my poor english, if I can look too rough.

I tried direct test, and had no problems with it.
On ws server side I can see some connections, going from ESTABLISHED to TIME_WAIT state after python script finish and exit.

Also `netstat -untap|grep fabio` does not show any stuck connections on fabio.

Do we have some way to debug underlying go library's deeper?

Thanks.

**Comment by leprechau** [comment] 2018-07-03 16:14
How long do the connections stay in `TIME_WAIT` and about how many are there?  I'm wondering if traefik is more aggressively closing sockets on behalf of the client.  Do you see the same number of `TIME_WAIT` connections with traefik and direct test?

**Closed** 2019-11-18 18:21 UTC
