### ISSUE TITLE
Add route based on x-forwarded-port header

### ISSUE THREAD

**Issue by jrasell** [fabiolb/fabio#450] opened 2018-02-26 11:51 UTC
I am not sure if this is currently possible and I have missed the documentation, apologies if it is. I would like to be able to add a route based on the value of an incoming header, specifically `x-forwarded-port` at this point. The reasoning behind this is that I currently have Fabio behind an ALB which does SSL offloading. A standard redirect results in a loop as Fabio will always see the traffic coming in as standard HTTP. I could use a network load balancer to pass traffic to Fabio and allow Fabio do the off-loading, however, I like some of the added security an ALB offers as it uses SGs and NLBs do not.

**Comment by jrasell** [comment] 2018-03-08 10:29
@leprechau thanks for the reply. The issue I am facing is that the ALB performs the SSL offload which means HTTPS traffic from the ALB appears to Fabio as only HTTP traffic and therefore does not currently allow me to use Fabio to perform the HTTP > HTTPS redirect as traffic gets stuck in a redirect loop. Allowing routes to be configured using the headers such as `x-forwarded-port` would allow me to resolve this situation be performing redirects based on the header which is added by the ALB and represents the client origin port, rather than the forwarded port.

**Comment by leprechau** [comment] 2018-03-08 12:53
Why do you need both fabio and the ALB to do redirects?

**Comment by jrasell** [comment] 2018-03-08 13:01
I don't; AWS ALBs do SSL offloading as standard and this behaviour cannot be changed from what I can see; ALBs do not do HTTP > HTTPS redirects. 

I could use a network load balancer and then use Fabio to do both the SSL offloading and redirection, but this would mean any IP whitelisting (I run services which are only exposed to internal ranges) would happen at the instance level (private subnet) where I prefer this to take place at the LB level (public subnet) thus meaning traffic doesn't get close to the servers.

**Comment by leprechau** [comment] 2018-03-08 13:11
Ohh, I see your problem.  The ALBs are forcing you to only pass plain HTTP without allowing you to force HTTPs incoming.

So, yes there are two options.

1. Make fabio look at the forwarded proto when it is processing redirects.

2. Just use fabio for both.  It does support IP access control now.  There was also a PR merged recently that will handle multi level proxy setups as well.

**Comment by jrasell** [comment] 2018-03-08 14:14
Exactly. So in my current setup supporting 1 would be excellent although I can indeed update my setup to use an NLB and let fabio do both redirect and SSL offloading if not.

**Comment by jrasell** [comment] 2018-03-15 08:06
@leprechau thanks for all the work, please close this ticket out as a duplicate if you wish and I can track 448.

**Comment by leprechau** [comment] 2018-03-16 13:05
@magiconair  can you close this as a dupe of #448?

**Closed** 2018-03-16 13:13 UTC
