### ISSUE TITLE
ability to remove headers from the request

### ISSUE THREAD

**Issue by samm-git** [fabiolb/fabio#528] opened 2018-08-06 20:24 UTC
Hi, i think it is more feature-request. 

I would like to remove some of the custom headers added by my load balancer to not expose their values to the registered services. In my configuration it would be enough to set value of this headers globally. I saw few tickets about "adding headers", so decided to add my usecase. If you think that it is something you would like to add - i can try to do a PR.

**Comment by leprechau** [comment] 2018-08-06 20:30
There has been quite a bit of discussion around header manipulation.

Most notably #110 and #168 which mention adding and removing headers.  I'm going to close this as a duplicate of #168 as I think that issue covers your use case.

Please feel free to on #168 with this use case.

**Closed by leprechau** 2018-08-06 20:30 UTC
